spring.application.name=products
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Crea/Actualiza tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Buenas Practicas
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logs
spring.jpa.show-sql=true